### ISSUE TITLE
[Feature request] develop branch support

### ISSUE THREAD

**Issue by enchained** [jlesage/docker-mkv-muxing-batch-gui#2]
### Idea

Latest release was in May 2, 2022 (v2.3), but since then the developer fulfilled a lot of the feature requests in the develop branch: https://github.com/yaser01/mkv-muxing-batch-gui/compare/main...develop

Is it possible to add support of this branch via a separate docker image tag?

**Comment by jlesage** [comment]
Do you know when the next version will be officially released ?

**Comment by enchained** [comment]
No, I could not find any info on that

**Comment by jlesage** [comment]
Version 2.4 has been integrated into the latest Docker image.  I think we can close this issue.
